# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productfeatured'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeatured',
            name='make_background',
            field=models.BooleanField(default=False),
        ),
    ]
